source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
target 'TTStaging' do
    pod 'TURecipientBar', '~> 2.0'
    pod 'AFNetworking', '~> 2.5'
    pod 'SDWebImage', '~>3.7'
    pod 'DNDDragAndDrop', '~> 1.1.0'
    pod 'FrameAccessor', '~> 2.0'
    pod 'IOSLinkedInAPI', '~> 2.0'
    pod 'IHKeyboardDismissing', '~> 1.1'
    pod 'FDKeychain', '~> 1.2'
    pod 'NSData+MD5Digest', '~> 1.0'
    pod 'UIAlertView-Blocks', '~> 1.0'
    pod 'JTMaterialSpinner', '~> 1.0'
    pod 'Mixpanel'
    pod 'GoogleAPIClientForREST', '~> 1.0'
    pod 'FBSDKCoreKit', '~> 4.13'
    pod 'FBSDKShareKit'
    pod 'FBSDKLoginKit'
    pod 'Fabric'
    pod 'Crashlytics'
end

target 'TalentTribe' do
    pod 'TURecipientBar', '~> 2.0'
    pod 'AFNetworking', '~> 2.5'
    pod 'SDWebImage', '~>3.7'
    pod 'DNDDragAndDrop', '~> 1.1.0'
    pod 'FrameAccessor', '~> 2.0'
    pod 'IOSLinkedInAPI', '~> 2.0'
    pod 'IHKeyboardDismissing', '~> 1.1'
    pod 'FDKeychain', '~> 1.2'
    pod 'NSData+MD5Digest', '~> 1.0'
    pod 'UIAlertView-Blocks', '~> 1.0'
    pod 'JTMaterialSpinner', '~> 1.0'
    pod 'Mixpanel'
    pod 'GoogleAPIClientForREST', '~> 1.0'
    pod 'FBSDKCoreKit', '~> 4.13'
    pod 'FBSDKShareKit'
    pod 'FBSDKLoginKit'
    pod 'Fabric'
    pod 'Crashlytics'
end